# Generated by Django 4.2.5 on 2024-01-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelAdmin', '0002_remove_paneladmin_diasservicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paneladmin',
            name='plan',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20),
        ),
    ]
