# Generated by Django 4.2.5 on 2024-01-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panelAdmin', '0003_paneladmin_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paneladmin',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
